apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: bare-metal
  source:
    path: gitops/argocd/apps/external-dns
    repoURL: https://github.com/satriashp/bare-metal.git
    targetRevision: main

  destination:
    name: "in-cluster"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
