apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: bare-metal
  source:
    path: gitops/argocd/apps/namespaces
    repoURL: https://github.com/satriashp/bare-metal.git
    targetRevision: main

  destination:
    name: "in-cluster"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
