#SPDX-License-Identifier: MIT-0
---
# tasks file for kubeadm
- name: Install kubectl
  ansible.builtin.include_tasks: kubectl.yaml

- name: Install kubelet
  ansible.builtin.include_tasks: kubelet.yaml

- name: Install kubeadm
  ansible.builtin.include_tasks: kubeadm.yaml
