resources:
  - namespaces/application.yaml
  - cert-manager/application.yaml
  - certificates/application.yaml
  - metal-lb/application.yaml
  - traefik/application.yaml
  - longhorn/application.yaml
  - monitoring/application.yaml
  - registry/application.yaml
