$ANSIBLE_VAULT;1.1;AES256
32306365633632653363366237366430343334623133633134623930373139656530623463346163
3536313938373639366561383666313330356437353831630a366630613630616138393861303634
38333366643539346166363966346461636537643038383739623138333363366433356464623237
3439663266343663390a376238646536306561383963313461656639613436306465373565326535
62653932326438623163623538653066376430383030336666656266646531616536353761333365
65653536643539333735633566363833336534643130373166613035346564396262366230653238
34313066343930346164353738666164633738363461313464346636393830663464383965306261
35366233376562333265626433633964343436636462653930663932333639383839636136393430
6338
