apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: bare-metal
  source:
    path: gitops/argocd/apps/certificates
    repoURL: https://github.com/satriashp/bare-metal.git
    targetRevision: main

  destination:
    name: "in-cluster"
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
