---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - "192.168.0.240/32"

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - default-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-pool
  namespace: metallb-system
spec:
  addresses:
    - "192.168.0.248/29"

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - public-pool
